import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useStella } from '../context/StellaContext';
import styles from './ReportsPage.module.css';

// ─── Static portfolio data ────────────────────────────────────────────────────

const KPI_CARDS = [
  { label: 'Total Active Claims', value: '121', sub: '+8 this week', subColor: '#d97706' },
  { label: 'Avg Cycle Time', value: '14.2 days', sub: '-1.4 vs last month', subColor: '#16a34a' },
  { label: 'Total Exposure', value: '$4.8M', sub: 'Open reserves', subColor: '#6366f1' },
  { label: 'SIU Referrals YTD', value: '7', sub: '4 closed, 3 active', subColor: '#e84040' },
  { label: 'Settled This Month', value: '34', sub: '$1.2M disbursed', subColor: '#16a34a' }
];

const PERIL_DATA = [
  { label: 'Water / Plumbing', count: 47, amount: 1820000, pct: 39, color: '#3b82f6' },
  { label: 'Wind / Hail / Roof', count: 31, amount: 1150000, pct: 26, color: '#6366f1' },
  { label: 'Fire / Smoke', count: 21, amount: 980000, pct: 17, color: '#e84040' },
  { label: 'Theft / Vandalism', count: 14, amount: 410000, pct: 12, color: '#f59e0b' },
  { label: 'Other / Liability', count: 8,  amount: 210000, pct: 6,  color: '#6b7280' }
];

const FRAUD_DIST = [
  { label: 'Low Risk', count: 74, pct: 61, color: '#16a34a' },
  { label: 'Medium Risk', count: 32, pct: 26, color: '#d97706' },
  { label: 'High Risk', count: 15, pct: 13, color: '#e84040' }
];

const REGIONAL_DATA = [
  { region: 'South Florida (Miami)', state: 'FL', claims: 28, exposure: 1340000, avgCycle: 18.4, fraudRate: '18%' },
  { region: 'Central Florida (Orlando)', state: 'FL', claims: 22, exposure: 980000, avgCycle: 12.1, fraudRate: '11%' },
  { region: 'Gulf Coast (Houston)', state: 'TX', claims: 19, exposure: 720000, avgCycle: 10.8, fraudRate: '8%' },
  { region: 'Atlanta Metro', state: 'GA', claims: 16, exposure: 590000, avgCycle: 11.2, fraudRate: '9%' },
  { region: 'Carolinas', state: 'NC/SC', claims: 14, exposure: 430000, avgCycle: 13.5, fraudRate: '7%' },
  { region: 'Other Regions', state: '—', claims: 22, exposure: 740000, avgCycle: 14.6, fraudRate: '10%' }
];

const ACTION_ITEMS = [
  { claimId: '2026-102', insured: 'Mary Johnson', peril: 'Fire', priority: 'HIGH', action: 'Structural assessment still missing — required before settlement', adjuster: 'Jane Doe', daysOpen: 12 },
  { claimId: '2026-108', insured: 'John Smith', peril: 'Water', priority: 'MEDIUM', action: 'Invoice address mismatch — request corrected invoice from Restoration Pro', adjuster: 'Jane Doe', daysOpen: 9 },
  { claimId: '2026-093', insured: 'Robert Davis', peril: 'Roof', priority: 'LOW', action: 'All documents complete — ready for payment authorization', adjuster: 'Jane Doe', daysOpen: 7 }
];

const SETTLEMENT_TREND = [
  { month: 'Jan', settled: 28, avgDays: 16.2 },
  { month: 'Feb', settled: 31, avgDays: 15.8 },
  { month: 'Mar', settled: 27, avgDays: 15.1 },
  { month: 'Apr', settled: 34, avgDays: 14.9 },
  { month: 'May', settled: 38, avgDays: 14.4 },
  { month: 'Jun', settled: 34, avgDays: 14.2 }
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmt(n) {
  if (n >= 1000000) return `$${(n / 1000000).toFixed(1)}M`;
  if (n >= 1000) return `$${(n / 1000).toFixed(0)}K`;
  return `$${n}`;
}

const PRIORITY_STYLE = {
  HIGH:   { bg: '#fee2e2', color: '#dc2626', border: '#fca5a5' },
  MEDIUM: { bg: '#fef3c7', color: '#d97706', border: '#fde68a' },
  LOW:    { bg: '#d1fae5', color: '#16a34a', border: '#a7f3d0' }
};

// ─── Component ────────────────────────────────────────────────────────────────

export default function ReportsPage() {
  const { updateContext } = useStella();
  const navigate = useNavigate();
  const maxPerilCount = Math.max(...PERIL_DATA.map(p => p.count));
  const maxSettled = Math.max(...SETTLEMENT_TREND.map(t => t.settled));

  useEffect(() => {
    updateContext({ page: 'reports', claimId: null, step: null });
  }, [updateContext]);

  return (
    <div className={styles.page}>
      <div className={styles.pageHeader}>
        <div>
          <h1 className={styles.title}>Claims Analytics & Reports</h1>
          <div className={styles.subtitle}>Homeowners P&amp;C Portfolio — YTD 2026 · Generated by Carrier AI</div>
        </div>
        <div className={styles.headerActions}>
          <button className="btn btn--outline btn--sm">Export PDF</button>
          <button className="btn btn--outline btn--sm">Export CSV</button>
        </div>
      </div>

      {/* KPI Row */}
      <div className={styles.kpiRow}>
        {KPI_CARDS.map(k => (
          <div key={k.label} className={styles.kpiCard}>
            <div className={styles.kpiValue}>{k.value}</div>
            <div className={styles.kpiLabel}>{k.label}</div>
            <div className={styles.kpiSub} style={{ color: k.subColor }}>{k.sub}</div>
          </div>
        ))}
      </div>

      {/* Charts Row */}
      <div className={styles.chartsRow}>

        {/* Claims by Peril */}
        <div className={styles.chartCard}>
          <div className={styles.chartTitle}>Claims by Peril Type</div>
          <div className={styles.chartSub}>Count and total exposure per peril</div>
          <div className={styles.perilChart}>
            {PERIL_DATA.map(p => (
              <div key={p.label} className={styles.perilRow}>
                <div className={styles.perilLabel}>{p.label}</div>
                <div className={styles.perilBarWrap}>
                  <div
                    className={styles.perilBar}
                    style={{ width: `${(p.count / maxPerilCount) * 100}%`, background: p.color }}
                  />
                </div>
                <div className={styles.perilStats}>
                  <span className={styles.perilCount}>{p.count}</span>
                  <span className={styles.perilAmount}>{fmt(p.amount)}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Fraud Risk Distribution */}
        <div className={styles.chartCard}>
          <div className={styles.chartTitle}>Fraud Risk Distribution</div>
          <div className={styles.chartSub}>121 claims assessed by Carrier AI</div>
          <div className={styles.fraudChart}>
            {FRAUD_DIST.map(f => (
              <div key={f.label} className={styles.fraudRow}>
                <div className={styles.fraudDot} style={{ background: f.color }} />
                <div className={styles.fraudLabel}>{f.label}</div>
                <div className={styles.fraudBarWrap}>
                  <div className={styles.fraudBar} style={{ width: `${f.pct}%`, background: f.color + '80' }} />
                </div>
                <div className={styles.fraudStats}>
                  <span className={styles.fraudCount} style={{ color: f.color }}>{f.count}</span>
                  <span className={styles.fraudPct}>{f.pct}%</span>
                </div>
              </div>
            ))}
          </div>
          <div className={styles.fraudNote}>
            ⚠ 15 High-risk claims require SIU review or are under active investigation
          </div>
        </div>

        {/* Settlement Trend */}
        <div className={styles.chartCard}>
          <div className={styles.chartTitle}>Monthly Settlement Trend</div>
          <div className={styles.chartSub}>Claims settled &amp; avg cycle time (days)</div>
          <div className={styles.trendChart}>
            {SETTLEMENT_TREND.map(t => (
              <div key={t.month} className={styles.trendCol}>
                <div className={styles.trendBarWrap}>
                  <div
                    className={styles.trendBar}
                    style={{ height: `${(t.settled / maxSettled) * 100}%` }}
                  />
                </div>
                <div className={styles.trendDays}>{t.avgDays}d</div>
                <div className={styles.trendMonth}>{t.month}</div>
              </div>
            ))}
          </div>
          <div className={styles.trendLegend}>
            <span className={styles.trendLegendBar} /> Settlements
            <span style={{ margin: '0 12px', color: '#d1d5db' }}>|</span>
            <span style={{ fontSize: 11, color: '#9ca3af' }}>Avg days label below each bar</span>
          </div>
        </div>

      </div>

      {/* Regional Breakdown */}
      <div className={styles.section}>
        <div className={styles.sectionTitle}>Regional Performance Breakdown</div>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Region</th>
              <th>State</th>
              <th>Claims</th>
              <th>Total Exposure</th>
              <th>Avg Cycle (days)</th>
              <th>Fraud Rate</th>
            </tr>
          </thead>
          <tbody>
            {REGIONAL_DATA.map(r => (
              <tr key={r.region}>
                <td>{r.region}</td>
                <td><span className={styles.stateBadge}>{r.state}</span></td>
                <td>{r.claims}</td>
                <td>{fmt(r.exposure)}</td>
                <td>
                  <span style={{ color: r.avgCycle > 15 ? '#dc2626' : r.avgCycle > 12 ? '#d97706' : '#16a34a', fontWeight: 600 }}>
                    {r.avgCycle}
                  </span>
                </td>
                <td>
                  <span style={{ color: parseFloat(r.fraudRate) > 15 ? '#dc2626' : parseFloat(r.fraudRate) > 10 ? '#d97706' : '#16a34a', fontWeight: 600 }}>
                    {r.fraudRate}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Open Action Items */}
      <div className={styles.section}>
        <div className={styles.sectionTitle}>Open Action Items — Requiring Adjuster Attention</div>
        <div className={styles.actionList}>
          {ACTION_ITEMS.map(item => {
            const pStyle = PRIORITY_STYLE[item.priority];
            return (
              <div
                key={item.claimId}
                className={styles.actionItem}
                onClick={() => navigate(`/claims/${item.claimId}/review?step=2`)}
              >
                <div className={styles.actionLeft}>
                  <span className={styles.actionPriority} style={{ background: pStyle.bg, color: pStyle.color, borderColor: pStyle.border }}>
                    {item.priority}
                  </span>
                  <div>
                    <div className={styles.actionTitle}>
                      <strong>#{item.claimId}</strong> — {item.insured}
                      <span className={styles.actionPeril}>{item.peril}</span>
                    </div>
                    <div className={styles.actionDesc}>{item.action}</div>
                  </div>
                </div>
                <div className={styles.actionRight}>
                  <div className={styles.actionAdjuster}>{item.adjuster}</div>
                  <div className={styles.actionDays}>{item.daysOpen}d open</div>
                  <span className={styles.actionArrow}>→</span>
                </div>
              </div>
            );
          })}
        </div>
      </div>

    </div>
  );
}
